### ISSUE TITLE
[FEAT] 받은편지, 보낸편지 UI

### ISSUE THREAD

**Issue by naerim** [eyear22/eyear_frontend#29]
## Issue

받은편지, 보낸편지 테이블 UI 생성

## Todo

- [x] 받은편지 UI 수정
- [x] 보낸편지 테이블 생성
- [x] 모바일용 화면 생성
