### ISSUE TITLE
[FEAT] 받은 편지 페이지 헤더 생성

### ISSUE THREAD

**Issue by naerim** [eyear22/eyear_frontend#31]
## Issue

받은 편지 페이지 UI 수정

## Todo

- [x] 카테고리 헤더 생성하기
- [x] API 연결하기
- [x] 모바일 화면 구성하기
- [x] 받은현지 테이블 수정하기
