### ISSUE TITLE
[FEAT] 공지사항, 환자관리 페이지

### ISSUE THREAD

**Issue by naerim** [eyear22/eyear_frontend#39]
## Issue

공지사항, 환자관리 페이지 완성하기

## Todo

- [x] 공지사항 페이지 UI
- [x] 환자관리 페이지 UI
- [x] 공지사항 api 연결
- [x] 환자리스트 api 연결
- [x] 환자 추가 api 연결
